### ISSUE TITLE
云星B250

### ISSUE THREAD

**Issue by Xiao-x7** [happytrudy/Redpill_Build#35]
"extra_cmdline": {
    "pid": "0x5678",
    "vid": "0x346D",
    "sn": "20B0SBR1Q62GV",
    "mac1": "9009D01B7505",
    "mac2": "C5834F275ACC",
    "netif_num": 2
  },

  "driver":"https://raw.githubusercontent.com/pocopico/rp-ext/master/r8125/rpext-index.json“,
  "dts":"https://github.com/chenxudong2020/Redpill_Build/files/11179420/output.dts.txt"

**Comment by happytrudy** [comment]
分析 title 和 body 内容 ..
> https://github.com/chenxudong2020/Redpill_Build/actions/runs/5823691914
----

**Comment by Xiao-x7** [comment]
"extra_cmdline": {
    "pid": "0x5678",
    "vid": "0x346D",
    "sn": "20B0SBR1Q62GV",
    "mac1": "9009D01B7505",
    "mac2": "C5834F275ACC",
    "netif_num": 2
  },

  "driver":"https://raw.githubusercontent.com/pocopico/rp-ext/master/r8125/rpext-index.json“,
  "dts":"https://github.com/chenxudong2020/Redpill_Build/files/11179420/output.dts.txt"

**Comment by happytrudy** [comment]
分析 title 和 body 内容 ..
> https://github.com/chenxudong2020/Redpill_Build/actions/runs/5838983997
----

**Comment by happytrudy** [comment]
超过3天暂时没时间处理，关闭issue
