### ISSUE TITLE
Custom j4125

### ISSUE THREAD

**Issue by Xiao-x7** [happytrudy/Redpill_Build#40]
{  
    
    "extra_cmdline": {
        "pid": "0x5678",
        "vid": "0x346D",
        "sn": "2040SBRD42CP2",
        "mac1": "9009D01B7505",
        "mac2": "C4834F275ACC",
        "netif_num": 2
      },
      "driver":"https://raw.githubusercontent.com/wjz304/rp-ext/master/modules/r8168/rpext-index.json",
      "dts":"https://cccimg.com/down.php/c7347a2acc4a248ef67997b1b6baa8b5.dts"       
      
    
}

**Comment by happytrudy** [comment]
Xiao-x7 您好.
您自定义的 DS920+ 版本: 7.2.0-64570 构建失败. 请前往下面的 URL 查看详细信息对body进行修改并请重新触发编译(Close & Reopen).
> https://github.com/chenxudong2020/Redpill_Build/actions/runs/6085862716

**Comment by happytrudy** [comment]
超过3天暂时没时间处理，关闭issue
