### ISSUE TITLE
万由401P 使用最新7.2.X引导，无M2缓存插槽

### ISSUE THREAD

**Issue by lp596108284** [happytrudy/Redpill_Build#47]
{  
    
    "extra_cmdline": {
        "pid": "0x5571",
        "vid": "0x0781",
        "sn": "2040SBRD42CP2",
        "mac1": "c4834f2742fa",
        "mac2": "c4834f2742fb",
        "netif_num": 2
      },
      "driver":"https://raw.githubusercontent.com/wjz304/rp-ext/master/modules/r8125/rpext-index.json,
                https://raw.githubusercontent.com/wjz304/rp-ext/main/modules/igc/rpext-index.json",
      "dts":"https://github.com/chenxudong2020/Redpill_Build/raw/master/dts/UNAS_T401P_ds920p.dts.txt"       
    
    
}

试过全新安装7.2.1系统，仍无法显示M2插槽，ssh命令行模式下可以正常查询m2硬盘信息。

目前将7.x版本全部进行测试，已知最高到7.1.X版本可正常显示并分配存储或缓存使用。再向上升级就无法显示跟使用了。

**Comment by happytrudy** [comment]
分析 title 和 body 内容 ..
> https://github.com/chenxudong2020/Redpill_Build/actions/runs/6875998657
----

**Comment by lp596108284** [comment]
不好意思，才发现更新通知里已删掉支持m2硬盘的描述
